{% set repo = "eigentest" %}
{% set version = "1.0.dev3" %}

package:
  name: "{{ repo|lower }}"
  version: "{{ version }}"

source:
  git_url: https://github.com/cffk/pdal-test.git
  git_rev: master

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('eigentest', max_pin='x.x') }}

requirements:
  build:
    - cmake
    - {{ compiler('cxx') }}
  host:
    - eigen
    - pdal=2.3
  run:
    - pdal=2.3
